---@meta

---@class classes
---@field Object Satisfactory.Components.Object
---@field Actor Satisfactory.Components.Actor
---@field ActorComponent Satisfactory.Components.ActorComponent
---@field ItemCategory Satisfactory.Components.ItemCategory
---@field ItemType Satisfactory.Components.ItemType
---@field PowerCircuit Satisfactory.Components.PowerCircuit
---@field Buildable Satisfactory.Components.Buildable
---@field Factory Satisfactory.Components.Factory
---@field FGBuildablePipelineAttachment Satisfactory.Components.FGBuildablePipelineAttachment
---@field PipelinePump Satisfactory.Components.PipelinePump
---@field Build_Valve_C Satisfactory.Components.Build_Valve_C
---@field FactoryConnection Satisfactory.Components.FactoryConnection
---@field Inventory Satisfactory.Components.Inventory
---@field PipeConnectionBase Satisfactory.Components.PipeConnectionBase
---@field PowerConnection Satisfactory.Components.PowerConnection
---@field PowerInfo Satisfactory.Components.PowerInfo
---@field ReflectionBase FIN.Components.ReflectionBase
---@field ComputerCase FIN.Components.ComputerCase
---@field ComputerCase_C FIN.Components.ComputerCase_C
---@field FINComputerModule FIN.Components.FINComputerModule
---@field FINInternetCard FIN.Components.FINInternetCard
---@field InternetCard_C FIN.Components.InternetCard_C
---@field NetworkCard FIN.Components.NetworkCard
---@field NetworkCard_C FIN.Components.NetworkCard_C
---@field Function FIN.Components.Function
---@field Property FIN.Components.Property
---@field Signal FIN.Components.Signal
---@field Struct FIN.Components.Struct
---@field ArrayProperty FIN.Components.ArrayProperty
---@field ClassProperty FIN.Components.ClassProperty
---@field ObjectProperty FIN.Components.ObjectProperty
---@field StructProperty FIN.Components.StructProperty
---@field TraceProperty FIN.Components.TraceProperty
---@field Class FIN.Components.Class
classes = {}

---@class structs
---@field Color Satisfactory.Components.Color
---@field Item Satisfactory.Components.Item
---@field ItemAmount Satisfactory.Components.ItemAmount
---@field ItemStack Satisfactory.Components.ItemStack
---@field Rotator Satisfactory.Components.Rotator
---@field Vector Satisfactory.Components.Vector
---@field Future FIN.Components.Future
---@field LogEntry FIN.Components.LogEntry
structs = {}
